// Rust emitter — walks the annotated AST and writes Rust source.
//
// DESIGN
//   The emitter uses an IndentWriter (a thin wrapper around String)
//   to manage indentation. Every emit_* method writes to the writer.
//   The final output is a single String containing a complete .rs file.
//
// OUTPUT STRUCTURE
//   #![no_std]
//   #![no_main]
//   // HAL imports
//   // Device struct definitions  (from DEFINE)
//   // impl blocks for each device struct
//   // Global variable declarations (from DECLARE)
//   // User functions (from FUNCTION)
//   // EVERY timer state (polling counters)
//   // #[entry] fn main()
//     // board init
//     // CREATE instantiations
//     // DECLARE initial values
//     // run_loop() call
//   // fn run_loop()  (contains RUN body)
//
// EVERY SCHEDULING MODEL
//   Uses a polling model for simplicity and board portability.
//   Each EVERY block gets a counter and a threshold in milliseconds.
//   The main loop tracks elapsed ms via a tick counter incremented
//   by the loop delay. When elapsed >= threshold, the block fires.
//
//   Generated pattern:
//     static mut EVERY_0_COUNTER: u64 = 0;
//     const  EVERY_0_PERIOD_MS:   u64 = 1000;
//
//     // inside run_loop():
//     unsafe { EVERY_0_COUNTER += LOOP_TICK_MS; }
//     if unsafe { EVERY_0_COUNTER } >= EVERY_0_PERIOD_MS {
//         unsafe { EVERY_0_COUNTER = 0; }
//         // EVERY body
//     }

use crate::ast::*;
use crate::codegen::context::{EmitContext};
use crate::codegen::name_mangler::{to_pascal, to_screaming_snake, to_snake};
use crate::codegen::type_map::{
    rust_device_arg, rust_device_param_type, rust_interface_field_type,
    rust_type, rust_type_for_data,
};

// ----------------------------------------------------------------
// IndentWriter
// ----------------------------------------------------------------

/// A string writer that tracks current indentation level.
/// Indentation is 4 spaces per level.
struct IndentWriter {
    buf:    String,
    indent: usize,
}

impl IndentWriter {
    fn new() -> Self {
        IndentWriter { buf: String::new(), indent: 0 }
    }

    fn indent(&mut self) { self.indent += 1; }
    fn dedent(&mut self) { if self.indent > 0 { self.indent -= 1; } }

    fn line(&mut self, s: &str) {
        if s.is_empty() {
            self.buf.push('\n');
        } else {
            for _ in 0..self.indent {
                self.buf.push_str("    ");
            }
            self.buf.push_str(s);
            self.buf.push('\n');
        }
    }

    fn blank(&mut self) { self.buf.push('\n'); }

    fn finish(self) -> String { self.buf }
}

// ----------------------------------------------------------------
// Emitter
// ----------------------------------------------------------------

pub struct Emitter<'a> {
    ctx:        &'a EmitContext,
    w:          IndentWriter,
    every_idx:  usize,
}

impl<'a> Emitter<'a> {
    pub fn new(ctx: &'a EmitContext) -> Self {
        Emitter { ctx, w: IndentWriter::new(), every_idx: 0 }
    }

    /// Emit a complete Rust source file from an annotated Program.
    pub fn emit(mut self, program: &Program) -> String {
        self.emit_file_header();
        self.emit_imports();
        self.blank();
        self.emit_device_structs(program);
        self.emit_global_declarations(program);
        self.emit_every_counters(program);
        self.blank();
        self.emit_user_functions(program);
        self.blank();
        self.emit_entry(program);
        self.w.finish()
    }

    // ── File header ──────────────────────────────────────────────

    fn emit_file_header(&mut self) {
        self.w.line("// Generated by the Ferrum compiler.");
        self.w.line("// Do not edit manually — regenerate from the .fe source file.");
        self.w.line("#![no_std]");
        self.w.line("#![no_main]");
        self.blank();
        // Optimization hints from CONFIG
        match self.ctx.optimize {
            crate::codegen::context::OptimizeLevel::Speed => {
                self.w.line("// CONFIG OPTIMIZE = \"speed\"");
                self.w.line("// Add to Cargo.toml: [profile.release] opt-level = 3");
            }
            crate::codegen::context::OptimizeLevel::Size => {
                self.w.line("// CONFIG OPTIMIZE = \"size\"");
                self.w.line("// Add to Cargo.toml: [profile.release] opt-level = \"s\"");
            }
            _ => {}
        }
    }

    // ── Imports ──────────────────────────────────────────────────

    fn emit_imports(&mut self) {
        let p = self.ctx.profile;
        self.w.line(&format!("use {}::entry;", p.hal_path));
        self.w.line(&format!("use {} as hal;", p.hal_path));
        self.w.line("use hal::prelude::*;");
        if self.ctx.debug {
            self.w.line("use defmt_rtt as _;");
            self.w.line("use panic_probe as _;");
        } else {
            self.w.line("use panic_halt as _;");
        }
    }

    // ── Device struct definitions (from DEFINE) ──────────────────
    //
    // DEFINE Led AS { OUTPUT, PWM BRIGHTNESS }
    // →
    // pub struct Led {
    //     pub output:     OutputPinType,
    //     pub brightness: PwmPinType,
    // }
    // impl Led {
    //     pub fn new(output: OutputPinType, brightness: PwmPinType) -> Self {
    //         Led { output, brightness }
    //     }
    // }

    fn emit_device_structs(&mut self, program: &Program) {
        for item in &program.defines {
            self.emit_device_struct(item);
            self.blank();
        }
    }

    fn emit_device_struct(&mut self, item: &DefineItem) {
        let struct_name = to_pascal(&item.name);
        let specs = match &item.spec {
            DeviceSpec::Simple(s)    => vec![s.clone()],
            DeviceSpec::Composite(v) => v.clone(),
        };

        // struct definition
        self.w.line(&format!("pub struct {} {{", struct_name));
        self.w.indent();
        for (i, spec) in specs.iter().enumerate() {
            let field_name = interface_field_name(spec, i);
            let field_type = rust_interface_field_type(self.ctx.profile, &spec.interface);
            self.w.line(&format!("pub {}: {},", field_name, field_type));
        }
        self.w.dedent();
        self.w.line("}");
        self.blank();

        // impl block with new()
        self.w.line(&format!("impl {} {{", struct_name));
        self.w.indent();

        // new() signature
        let params: Vec<String> = specs.iter().enumerate().map(|(i, spec)| {
            format!("{}: {}",
                interface_field_name(spec, i),
                rust_interface_field_type(self.ctx.profile, &spec.interface)
            )
        }).collect();
        self.w.line(&format!("pub fn new({}) -> Self {{", params.join(", ")));
        self.w.indent();

        // struct initialiser body
        self.w.line(&format!("{} {{", struct_name));
        self.w.indent();
        for (i, spec) in specs.iter().enumerate() {
            let fname = interface_field_name(spec, i);
            self.w.line(&format!("{},", fname));
        }
        self.w.dedent();
        self.w.line("}");
        self.w.dedent();
        self.w.line("}");
        self.w.dedent();
        self.w.line("}");
    }

    // ── Global declarations (from DECLARE) ───────────────────────
    //
    // DECLARE Integer counter INIT 0
    // → static mut COUNTER: i32 = 0;
    //
    // DECLARE CONSTANT Integer MAX = 100
    // → const MAX: i32 = 100;

    fn emit_global_declarations(&mut self, program: &Program) {
        for item in &program.declares {
            match &item.kind {
                DeclareKind::Constant(c) => {
                    let name = to_screaming_snake(&c.name);
                    let ty   = rust_type_for_data(&c.ty);
                    let val  = emit_literal(&c.value);
                    self.w.line(&format!("const {}: {} = {};", name, ty, val));
                }
                DeclareKind::Variable(v) => {
                    let name = to_snake(&v.name).to_uppercase();
                    let ty   = if let Some(size) = v.array_size {
                        format!("[{}; {}]", rust_type_for_data(&v.ty), size)
                    } else {
                        rust_type_for_data(&v.ty).to_string()
                    };
                    let init = match &v.init {
                        Some(InitExpr::Single(lit)) => emit_literal(lit),
                        Some(InitExpr::Array(lits)) => {
                            let elems: Vec<String> = lits.iter().map(emit_literal).collect();
                            format!("[{}]", elems.join(", "))
                        }
                        None => default_for_data_type(&v.ty).to_string(),
                    };
                    // Program-level variables use static mut
                    self.w.line(&format!("static mut {}: {} = {};", name, ty, init));
                    // If this is an array, also emit a parallel fill-level counter
                    if let Some(size) = v.array_size {
                        // Determine initial fill level: if fully-initialised with an array literal,
                        // set to the literal length; otherwise start at 0.
                        let initial_len = match &v.init {
                            Some(InitExpr::Array(lits)) => lits.len(),
                            _ => 0,
                        };
                        self.w.line(&format!(
                            "static mut {}_LEN: usize = {};",
                            name, // NAME_LEN (matches emitter usage)
                            initial_len
                        ));
                    }
                }
            }
        }
        if !program.declares.is_empty() { self.blank(); }
    }

    // ── EVERY counters ───────────────────────────────────────────

    fn emit_every_counters(&mut self, program: &Program) {
        let everys = collect_every_blocks(&program.run);
        if everys.is_empty() { return; }

        self.w.line("// EVERY block scheduling counters (polling model)");
        self.w.line("const LOOP_TICK_MS: u64 = 10; // main loop tick interval");
        for (i, block) in everys.iter().enumerate() {
            self.w.line(&format!(
                "static mut EVERY_{}_COUNTER: u64 = 0;",
                i
            ));
            self.w.line(&format!(
                "const  EVERY_{}_PERIOD_MS:   u64 = {};",
                i, block.period.as_millis()
            ));
        }
        self.blank();
    }

    // ── User functions (from FUNCTION) ───────────────────────────
    //
    // FUNCTION add Integer: a, Integer: b { RETURN a + b }
    // →
    // fn add(a: i32, b: i32) -> i32 {
    //     a + b
    // }
    //
    // FUNCTION pulse BORROW Led: led { TURN led HIGH ... }
    // →
    // fn pulse(led: &mut Led) {
    //     led.output.set_high().unwrap();
    //     ...
    // }

    fn emit_user_functions(&mut self, program: &Program) {
        for func in &program.functions {
            self.emit_function(func);
            self.blank();
        }
    }

    fn emit_function(&mut self, func: &FunctionDef) {
        let fn_name = to_snake(&func.name);

        // Build parameter list
        let params: Vec<String> = func.params.iter().map(|p| match p {
            Param::Data { ty, name, .. } => {
                format!("{}: {}", to_snake(name), rust_type_for_data(ty))
            }
            Param::Device { ownership, device_ty, name, .. } => {
                let type_name = to_pascal(device_ty);
                let rust_ty   = rust_device_param_type(&type_name, ownership);
                format!("{}: {}", to_snake(name), rust_ty)
            }
        }).collect();

        // Return type
        let ret_ty = match &func.return_type {
            Some(t) if *t != Type::Void => format!(" -> {}", rust_type(t)),
            _ => String::new(),
        };

        self.w.line(&format!("fn {}({}){} {{", fn_name, params.join(", "), ret_ty));
        self.w.indent();

        for stmt in &func.body {
            self.emit_statement(stmt);
        }
        if let Some(ret) = &func.ret {
            if let Some(expr) = &ret.value {
                self.w.line(&emit_expr(expr));
            }
        }

        self.w.dedent();
        self.w.line("}");
    }

    // ── #[entry] main() ──────────────────────────────────────────

    fn emit_entry(&mut self, program: &Program) {
        self.w.line("#[entry]");
        self.w.line("fn main() -> ! {");
        self.w.indent();

        // Board init boilerplate
        for line in self.ctx.profile.board_init.lines() {
            self.w.line(line);
        }
        self.blank();

        // CREATE instantiations
        self.emit_create_instantiations(program);

        // Apply INIT states
        self.emit_init_states(program);

        self.blank();
        self.w.line("run_loop(");

        // Pass all device instances to run_loop
        let device_args: Vec<String> = program.creates.iter()
            .map(|c| format!("&mut {}", to_snake(&c.instance_name)))
            .collect();
        if !device_args.is_empty() {
            self.w.indent();
            for arg in &device_args {
                self.w.line(&format!("{},", arg));
            }
            self.w.dedent();
        }

        self.w.line(");");
        self.w.dedent();
        self.w.line("}");
        self.blank();

        // run_loop() signature + body
        self.emit_run_loop(program);
    }

    // ── CREATE instantiations ────────────────────────────────────
    //
    // CREATE Led status ON { output: PIN 3, brightness: PIN 4 }
    // →
    // let mut status = Led::new(
    //     pins.gpio3.into_push_pull_output(),
    //     pins.gpio4.into_pwm_output(),
    // );

    fn emit_create_instantiations(&mut self, program: &Program) {
        for item in &program.creates {
            let inst   = to_snake(&item.instance_name);
            let struct_ = to_pascal(&item.device_type);

            // Collect pin expressions in interface order
            let pin_exprs = self.pin_exprs_for(item);

            if pin_exprs.len() == 1 {
                self.w.line(&format!(
                    "let mut {} = {}::new({});",
                    inst, struct_, pin_exprs[0]
                ));
            } else {
                self.w.line(&format!("let mut {} = {}::new(", inst, struct_));
                self.w.indent();
                for expr in &pin_exprs {
                    self.w.line(&format!("{},", expr));
                }
                self.w.dedent();
                self.w.line(");");
            }
        }
        if !program.creates.is_empty() { self.blank(); }
    }

    fn pin_exprs_for(&self, item: &CreateItem) -> Vec<String> {
        let pin_access_tmpl = self.ctx.profile.pin_access;
        match &item.pins {
            PinSpec::Single { pin, .. } => {
                vec![pin_access_tmpl.replace("{N}", &pin.to_string())]
            }
            PinSpec::Multi(assignments) => {
                assignments.iter()
                    .map(|a| pin_access_tmpl.replace("{N}", &a.pin_number.to_string()))
                    .collect()
            }
        }
    }

    // ── INIT state application ───────────────────────────────────
    //
    // INIT { output: LOW, brightness: 0.0 }
    // →
    // status.output.set_low().unwrap();
    // status.brightness.set_duty(0.0);

    fn emit_init_states(&mut self, program: &Program) {
        for item in &program.creates {
            if let Some(init) = &item.init {
                let inst = to_snake(&item.instance_name);
                for entry in &init.values {
                    let field = entry.interface_name.as_ref()
                        .map(|i| to_snake(i))
                        .unwrap_or_else(|| "output".into());
                    let init_call = match &entry.value {
                        InitValue::High       => format!("{}.{}.set_high().unwrap();", inst, field),
                        InitValue::Low        => format!("{}.{}.set_low().unwrap();", inst, field),
                        InitValue::Decimal(f) => format!("{}.{}.set_duty({}_f32);", inst, field, f),
                        InitValue::Str(s)     => format!("{}.{}.write_str(\"{}\").unwrap();", inst, field, s),
                        InitValue::Int(n)     => format!("{}.{}.write_str(\"{}\").unwrap();", inst, field, n),
                    };
                    self.w.line(&init_call);
                }
            }
        }
    }

    // ── run_loop() ───────────────────────────────────────────────
    //
    // Contains the RUN section body.
    // Device instances are received as &mut parameters.

    fn emit_run_loop(&mut self, program: &Program) {
        // Build run_loop signature — all devices as &mut params
        let params: Vec<String> = program.creates.iter().map(|c| {
            format!(
                "{}: &mut {}",
                to_snake(&c.instance_name),
                to_pascal(&c.device_type)
            )
        }).collect();

        self.w.line(&format!("fn run_loop({}) -> ! {{", params.join(", ")));
        self.w.indent();

        // Reset every index for this emission
        self.every_idx = 0;

        for item in &program.run.items {
            self.emit_run_item(item);
        }

        // Fallback loop if no LOOP block — keeps the function returning !
        let has_loop = program.run.items.iter().any(|i| matches!(i, RunItem::Loop(_)));
        if !has_loop {
            self.w.line("loop {}");
        }

        self.w.dedent();
        self.w.line("}");
    }

    fn emit_run_item(&mut self, item: &RunItem) {
        match item {
            RunItem::Every(e)  => self.emit_every_block(e),
            RunItem::Loop(l)   => self.emit_loop_block(l),
            RunItem::TopIf(t)  => self.emit_top_if(t),
            RunItem::Stmt(s)   => self.emit_statement(s),
        }
    }

    // ── EVERY block ──────────────────────────────────────────────
    //
    // EVERY 1000ms { PRINT "tick" }
    // →
    // unsafe { EVERY_0_COUNTER += LOOP_TICK_MS; }
    // if unsafe { EVERY_0_COUNTER } >= EVERY_0_PERIOD_MS {
    //     unsafe { EVERY_0_COUNTER = 0; }
    //     // body
    // }

    fn emit_every_block(&mut self, block: &EveryBlock) {
        let idx = self.every_idx;
        self.every_idx += 1;

        self.w.line(&format!(
            "unsafe {{ EVERY_{}_COUNTER += LOOP_TICK_MS; }}",
            idx
        ));
        self.w.line(&format!(
            "if unsafe {{ EVERY_{}_COUNTER }} >= EVERY_{}_PERIOD_MS {{",
            idx, idx
        ));
        self.w.indent();
        self.w.line(&format!("unsafe {{ EVERY_{}_COUNTER = 0; }}", idx));
        for stmt in &block.body {
            self.emit_statement(stmt);
        }
        self.w.dedent();
        self.w.line("}");
    }

    fn emit_top_if(&mut self, block: &TopIfBlock) {
        let cond = emit_expr(&block.condition);
        self.w.line(&format!("if {} {{", cond));
        self.w.indent();
        for item in &block.then_items { self.emit_run_item(item); }
        self.w.dedent();
        if let Some(else_items) = &block.else_items {
            self.w.line("} else {");
            self.w.indent();
            for item in else_items { self.emit_run_item(item); }
            self.w.dedent();
        }
        self.w.line("}");
    }

    fn emit_loop_block(&mut self, block: &LoopBlock) {
        self.w.line("loop {");
        self.w.indent();
        for stmt in &block.body {
            self.emit_statement(stmt);
        }
        self.w.dedent();
        self.w.line("}");
    }

    // ── Statements ───────────────────────────────────────────────

    fn emit_statement(&mut self, stmt: &Statement) {
        match &stmt.kind {
            StmtKind::Assignment(s) => {
                let target = to_snake(&s.target).to_uppercase();
                let val    = emit_expr(&s.value);
                self.w.line(&format!("unsafe {{ {} = {}; }}", target, val));
            }

            StmtKind::Turn(s) => {
                let inst  = to_snake(&s.device);
                let field = s.qualifier.as_ref()
                    .map(|q| qualifier_field_name(q))
                    .unwrap_or("output");
                let call  = match s.state {
                    PinState::High => "set_high().unwrap()",
                    PinState::Low  => "set_low().unwrap()",
                };
                self.w.line(&format!("{}.{}.{};", inst, field, call));
            }
            
            StmtKind::Set(s) => {
                let inst      = to_snake(&s.device);
                let field     = s.qualifier.as_ref()
                    .map(|q| qualifier_field_name(q))
                    .unwrap_or("output");
                let val       = emit_expr(&s.value);
                self.w.line(&format!("{}.{}.set_duty({});", inst, field, val));
            }

            StmtKind::Toggle(s) => {
                let inst  = to_snake(&s.device);
                self.w.line(&format!("{}.output.toggle().unwrap();", inst));
            }

            StmtKind::Print(s) => {
                if self.ctx.debug {
                    let val = emit_expr(&s.value);
                    self.w.line(&format!("defmt::println!(\"{{}}\", {});", val));
                }
                // Compiled out entirely when debug = false
            }

            StmtKind::VoidCall(s) => {
                self.emit_call_stmt(s);
            }

            StmtKind::Delay(s) => {
                let ms   = s.duration.as_millis();
                let call = self.ctx.profile.delay_ms
                    .replace("{MS}", &ms.to_string());
                self.w.line(&format!("{};", call));
            }

            StmtKind::If(s) => self.emit_if_stmt(s),
            StmtKind::For(s) => self.emit_for_stmt(s),

            StmtKind::Break    => self.w.line("break;"),
            StmtKind::Continue => self.w.line("continue;"),

            StmtKind::InlineDeclare(s) => self.emit_inline_declare(s),
        }
    }

    fn emit_call_stmt(&mut self, stmt: &CallStmt) {
        if let Some(builtin) = builtin_rust_name(&stmt.function.key) {
            let args = self.format_call_args(&stmt.args);
            self.w.line(&format!("{};", builtin_call(builtin, &stmt.args)));
        } else {
            let fn_name = to_snake(&stmt.function);
            let args    = self.format_call_args(&stmt.args);
            self.w.line(&format!("{}({});", fn_name, args));
        }
    }

    fn emit_if_stmt(&mut self, stmt: &IfStmt) {
        let cond = emit_expr(&stmt.condition);
        self.w.line(&format!("if {} {{", cond));
        self.w.indent();
        for s in &stmt.then_body { self.emit_statement(s); }
        self.w.dedent();
        match &stmt.else_body {
            Some(ElseClause::Block(stmts)) => {
                self.w.line("} else {");
                self.w.indent();
                for s in stmts { self.emit_statement(s); }
                self.w.dedent();
                self.w.line("}");
            }
            None => self.w.line("}"),
        }
    }

    fn emit_for_stmt(&mut self, stmt: &ForStmt) {
        let var = to_snake(&stmt.variable);
        let iter = match &stmt.iterator {
            ForIterator::Array(expr)          => emit_expr(expr) + ".iter()",
            ForIterator::Range { from, to }   => {
                format!("{}..={}", emit_expr(from), emit_expr(to))
            }
        };
        self.w.line(&format!("for {} in {} {{", var, iter));
        self.w.indent();
        for s in &stmt.body { self.emit_statement(s); }
        self.w.dedent();
        self.w.line("}");
    }

    fn emit_inline_declare(&mut self, stmt: &InlineDeclareStmt) {
        let name = to_snake(&stmt.name);
        let ty   = if let Some(size) = stmt.array_size {
            format!("[{}; {}]", rust_type_for_data(&stmt.ty), size)
        } else {
            rust_type_for_data(&stmt.ty).to_string()
        };
        let val  = match &stmt.init {
            InlineDeclareInit::Value(InitExpr::Single(lit)) => emit_literal(lit),
            InlineDeclareInit::Value(InitExpr::Array(lits)) => {
                let elems: Vec<String> = lits.iter().map(emit_literal).collect();
                format!("[{}]", elems.join(", "))
            }
            InlineDeclareInit::Call(call) => {
                let fn_name = to_snake(&call.function);
                let args    = self.format_call_args(&call.args);
                format!("{}({})", fn_name, args)
            }
        };
        self.w.line(&format!("let {}: {} = {};", name, ty, val));
        // If this is a block-scoped array, emit a fill-level counter variable
        if let Some(_size) = stmt.array_size {
            let initial_len = match &stmt.init {
                InlineDeclareInit::Value(InitExpr::Array(lits)) => lits.len(),
                _ => 0,
            };
            self.w.line(&format!("let mut {}_len: usize = {};", name, initial_len));
        }
    }

    // ── Call argument formatting ──────────────────────────────────

    fn format_call_args(&self, args: &[CallArg]) -> String {
        args.iter().map(|arg| match &arg.kind {
            CallArgKind::Data(expr) => emit_expr(expr),
            CallArgKind::Device { ownership, name } => {
                let n = to_snake(name);
                rust_device_arg(&n, ownership)
            }
        }).collect::<Vec<_>>().join(", ")
    }

    fn blank(&mut self) { self.w.blank(); }
}

// ----------------------------------------------------------------
// Pure expression emitter (no indentation needed)
// ----------------------------------------------------------------

/// Emit an expression as a Rust expression string.
/// Called recursively; does not write to the IndentWriter directly.
fn emit_expr(expr: &Expr) -> String {
    match &expr.kind {

        ExprKind::Literal(lit) => emit_literal(lit),

        ExprKind::Ident(ident) => {
            // Program-level variables are static mut — wrap in unsafe read
            // Block-scoped variables are let bindings — plain name
            // The distinction is tracked by whether the ident is uppercase
            // in the emitted names (program-level = UPPERCASE_SNAKE).
            // For simplicity emit as lowercase; the caller knows context.
            to_snake(ident)
        }

        ExprKind::Read(device) => {
            let inst = to_snake(device);
            // INPUT → is_high() returns bool (HIGH=true, LOW=false)
            // ANALOG_INPUT → read() returns u16
            // Type is filled by semantic pass; use it to decide
            match &expr.ty {
                Some(Type::PinState)  => format!("{}.output.is_high().unwrap()", inst),
                Some(Type::AnalogRaw) => format!("{}.output.read()", inst),
                _                     => format!("{}.output.is_high().unwrap()", inst),
            }
        }

        ExprKind::ReadPercent(device) => {
            let inst = to_snake(device);
            // READ_PERCENT → read raw, scale to 0.0–100.0
            format!("({}.output.read() as f32 / 1023.0 * 100.0)", inst)
        }

        ExprKind::BinOp { op, left, right } => {
            let l = emit_expr(left);
            let r = emit_expr(right);
            match op {
                BinOp::Add   => format!("({} + {})",  l, r),
                BinOp::Sub   => format!("({} - {})",  l, r),
                BinOp::Mul   => format!("({} * {})",  l, r),
                BinOp::Div   => format!("({} / {})",  l, r),
                BinOp::Gt    => format!("({} > {})",  l, r),
                BinOp::Lt    => format!("({} < {})",  l, r),
                BinOp::Gte   => format!("({} >= {})", l, r),
                BinOp::Lte   => format!("({} <= {})", l, r),
                BinOp::Eq    => format!("({} == {})", l, r),
                BinOp::NotEq => format!("({} != {})", l, r),
                BinOp::And   => format!("({} && {})", l, r),
                BinOp::Or    => format!("({} || {})", l, r),
            }
        }

        ExprKind::UnaryOp { op, operand } => {
            let o = emit_expr(operand);
            match op {
                UnaryOp::Not => format!("(!{})", o),
                UnaryOp::Neg => format!("(-{})", o),
            }
        }

        ExprKind::Is { target, negated, state } => {
            // mode_btn IS LOW    → mode_btn.output.is_low().unwrap()
            // auto_mode IS TRUE  → auto_mode == true   → auto_mode
            // IS NOT             → negated form
            let target_str = if let ExprKind::Ident(i) = &target.kind {
                to_snake(i)
            } else {
                emit_expr(target)
            };

            let state_str = emit_expr(state);

            // If checking a pin state (HIGH/LOW), use HAL method
            let base = match &state.kind {
                ExprKind::Literal(Literal::High) =>
                    format!("{}.output.is_high().unwrap()", target_str),
                ExprKind::Literal(Literal::Low) =>
                    format!("{}.output.is_low().unwrap()", target_str),
                ExprKind::Literal(Literal::Bool(b)) => {
                    if *b { target_str.clone() }
                    else  { format!("(!{})", target_str) }
                }
                _ => format!("({} == {})", target_str, state_str),
            };

            if *negated { format!("(!{})", base) } else { base }
        }

        ExprKind::Call(call) => {
            let fn_name = to_snake(&call.function);
            let args: Vec<String> = call.args.iter().map(|arg| match &arg.kind {
                CallArgKind::Data(e) => emit_expr(e),
                CallArgKind::Device { ownership, name } => {
                    rust_device_arg(&to_snake(name), ownership)
                }
            }).collect();
            format!("{}({})", fn_name, args.join(", "))
        }

        ExprKind::IfExpr { condition, then_value, else_value } => {
            format!(
                "if {} {{ {} }} else {{ {} }}",
                emit_expr(condition),
                emit_expr(then_value),
                emit_expr(else_value)
            )
        }
    }
}

fn emit_literal(lit: &Literal) -> String {
    match lit {
        Literal::Int(n)     => n.to_string(),
        Literal::Hex(n)     => format!("0x{:X}_u8", n),
        Literal::Decimal(f) => format!("{}_f32", f),
        Literal::Str(s)     => format!("\"{}\"", s),
        Literal::Bool(b)    => if *b { "true".into() } else { "false".into() },
        Literal::High       => "true".into(),
        Literal::Low        => "false".into(),
    }
}

// ----------------------------------------------------------------
// Helpers
// ----------------------------------------------------------------

/// Generate a Rust field name for a device struct interface at position i.
fn interface_field_name(spec: &InterfaceSpec, index: usize) -> String {
    if let Some(q) = &spec.qualifier {
        qualifier_field_name(q).to_string()
    } else {
        match spec.interface {
            InterfaceType::Output      => "output".into(),
            InterfaceType::Input       => "input".into(),
            InterfaceType::AnalogInput => "analog".into(),
            InterfaceType::Pwm         => format!("pwm_{}", index),
            InterfaceType::Display     => "display".into(),
            InterfaceType::Pulse       => if index == 0 { "trigger".into() } else { "echo".into() },
        }
    }
}

fn qualifier_field_name(q: &Qualifier) -> &'static str {
    match q {
        Qualifier::Brightness => "brightness",
        Qualifier::Speed      => "speed",
        Qualifier::Angle      => "angle",
        Qualifier::Red        => "red",
        Qualifier::Green      => "green",
        Qualifier::Blue       => "blue",
        Qualifier::Lcd        => "display",
        Qualifier::Oled       => "display",
        Qualifier::Trigger    => "trigger",
        Qualifier::Echo       => "echo",
        Qualifier::Enable     => "enable",
    }
}

fn default_for_data_type(ty: &DataType) -> &'static str {
    match ty {
        DataType::Integer    => "0",
        DataType::Decimal    => "0.0_f32",
        DataType::Percentage => "0.0_f32",
        DataType::Boolean    => "false",
        DataType::String     => "\"\"",
        DataType::Byte       => "0u8",
    }
}

/// Collect all EVERY blocks from a RUN section (recursing into TopIf).
fn collect_every_blocks(run: &RunSection) -> Vec<&EveryBlock> {
    let mut blocks = Vec::new();
    for item in &run.items {
        collect_every_in_run_item(item, &mut blocks);
    }
    blocks
}

fn collect_every_in_run_item<'a>(item: &'a RunItem, out: &mut Vec<&'a EveryBlock>) {
    match item {
        RunItem::Every(e) => out.push(e),
        RunItem::TopIf(t) => {
            for i in &t.then_items { collect_every_in_run_item(i, out); }
            if let Some(els) = &t.else_items {
                for i in els { collect_every_in_run_item(i, out); }
            }
        }
        _ => {}
    }
}

fn builtin_rust_name(key: &str) -> Option<&'static str> {
    match key {
        "abs"            => Some("ferrum_stdlib::abs"),
        "min"            => Some("ferrum_stdlib::min"),
        "max"            => Some("ferrum_stdlib::max"),
        "clamp"          => Some("ferrum_stdlib::clamp"),
        "map"            => Some("ferrum_stdlib::map"),
        "to_integer"     => Some("ferrum_stdlib::to_integer"),
        "to_decimal"     => Some("ferrum_stdlib::to_decimal"),
        "to_percentage"  => Some("ferrum_stdlib::to_percentage"),
        "to_string"      => Some("ferrum_stdlib::integer_to_string"), // overloaded — resolved by type_checker
        "length"         => None, // resolved by type_checker to str_length or array_length
        "includes"       => Some("ferrum_stdlib::includes"),
        "add"            => Some("ferrum_stdlib::array_add"),
        "remove"         => Some("ferrum_stdlib::array_remove"),
        _                => None,
    }
}

/// Format a complete Rust expression for a built-in function call.
/// `builtin` is the resolved Rust path from builtin_rust_name().
/// `args` are the original Ferrum call arguments.
fn builtin_call(builtin: &str, args: &[CallArg]) -> String {
    // Format all data arguments as Rust expressions.
    // Built-in functions never take device arguments, so
    // CallArgKind::Device is not expected here — but we guard anyway.
    let exprs: Vec<String> = args.iter().filter_map(|a| {
        match &a.kind {
            CallArgKind::Data(e) => Some(emit_expr(e)),
            CallArgKind::Device { .. } => None, // unreachable for builtins
        }
    }).collect();

    match builtin {
        // ── length is overloaded ──────────────────────────────────
        // Resolved at this point by checking the first argument's type.
        // str_length takes a &str.
        // array_length takes the fill-level usize, not the slice itself.
        // The emitter passes the logical length variable which the
        // semantic pass tracks alongside each array declaration.
        "ferrum_stdlib::str_length" => {
            format!("ferrum_stdlib::str_length({})", exprs.join(", "))
        }
        "ferrum_stdlib::array_length" => {
            // array_length(len) — the fill-level variable, not the slice
            // The emitter names fill-level vars as: {array_name}_len
            // e.g. DECLARE Integer[5] readings → readings_len: usize
            let arr_name = exprs.first().cloned().unwrap_or_default();
            format!("ferrum_stdlib::array_length({}_len)", arr_name)
        }

        // ── ADD and REMOVE mutate in place ────────────────────────
        // ADD array, value  →  array_add(&mut array, &mut array_len, value)
        // REMOVE array, idx →  array_remove(&mut array, &mut array_len, idx)
        "ferrum_stdlib::array_add" => {
            let arr   = exprs.get(0).cloned().unwrap_or_default();
            let value = exprs.get(1).cloned().unwrap_or_default();
            format!(
                "ferrum_stdlib::array_add(&mut {}, &mut {}_len, {})",
                arr, arr, value
            )
        }
        "ferrum_stdlib::array_remove" => {
            let arr = exprs.get(0).cloned().unwrap_or_default();
            let idx = exprs.get(1).cloned().unwrap_or_default();
            format!(
                "ferrum_stdlib::array_remove(&mut {}, &mut {}_len, {} as usize)",
                arr, arr, idx
            )
        }

        // ── to_string is overloaded ───────────────────────────────
        // The semantic pass filled Expr.ty on the first argument.
        // Read it to pick the right formatter.
        // All formatters need a FmtBuf — the emitter injects a
        // thread-local (actually stack-local) buf at the call site.
        "ferrum_stdlib::to_string" => {
            let val = exprs.first().cloned().unwrap_or_default();
            // Peek at the resolved type of the first argument
            let ty = args.first()
                .and_then(|a| match &a.kind {
                    CallArgKind::Data(e) => e.ty.as_ref(),
                    _ => None,
                });
            let formatter = match ty {
                Some(Type::Integer)    => "ferrum_stdlib::integer_to_string",
                Some(Type::Decimal)    => "ferrum_stdlib::decimal_to_string",
                Some(Type::Percentage) => "ferrum_stdlib::percentage_to_string",
                Some(Type::Byte)       => "ferrum_stdlib::byte_to_string",
                Some(Type::Boolean)    => {
                    // Boolean to_string doesn't need a buf — return directly
                    return format!("ferrum_stdlib::boolean_to_string({})", val);
                }
                _ => "ferrum_stdlib::integer_to_string", // fallback
            };
            // Non-boolean formatters need a stack buffer
            format!("{{ let mut _buf = ferrum_stdlib::FmtBuf::new(); {formatter}({val}, &mut _buf) }}")
        }

        // ── map needs all 5 arguments as f32 ─────────────────────
        // Ferrum: map value, from_low, from_high, to_low, to_high
        // All args cast to f32 for the Decimal return type.
        "ferrum_stdlib::map" => {
            let casted: Vec<String> = exprs.iter()
                .map(|e| format!("({}) as f32", e))
                .collect();
            format!("ferrum_stdlib::map({})", casted.join(", "))
        }

        // ── Everything else: straight call ────────────────────────
        // abs, min, max, clamp, to_integer, to_decimal,
        // to_percentage, includes — all take plain args.
        _ => {
            format!("{}({})", builtin, exprs.join(", "))
        }
    }
}

#[cfg(test)]
mod rust_emit_tests {
    use super::*;
    use crate::codegen::context::EmitContext;

    fn ctx() -> EmitContext {
        EmitContext::from_config(&None).unwrap()
    }

    #[test]
    fn emit_literal_integer() {
        assert_eq!(emit_literal(&Literal::Int(42)), "42");
    }

    #[test]
    fn emit_literal_decimal() {
        assert_eq!(emit_literal(&Literal::Decimal(3.14)), "3.14_f32");
    }

    #[test]
    fn emit_literal_bool_true() {
        assert_eq!(emit_literal(&Literal::Bool(true)), "true");
    }

    #[test]
    fn emit_literal_high_is_true() {
        assert_eq!(emit_literal(&Literal::High), "true");
    }

    #[test]
    fn emit_literal_low_is_false() {
        assert_eq!(emit_literal(&Literal::Low), "false");
    }

    #[test]
    fn emit_binop_add() {
        use std::sync::Arc;
        use crate::lexer::token::Span;
        let span = Span::new(Arc::new("t.fe".into()), 1, 1, 1);
        let expr = Expr {
            kind: ExprKind::BinOp {
                op:    BinOp::Add,
                left:  Box::new(Expr { kind: ExprKind::Literal(Literal::Int(3)), ty: Some(Type::Integer), span: span.clone() }),
                right: Box::new(Expr { kind: ExprKind::Literal(Literal::Int(4)), ty: Some(Type::Integer), span: span.clone() }),
            },
            ty:   Some(Type::Integer),
            span,
        };
        assert_eq!(emit_expr(&expr), "(3 + 4)");
    }

    #[test]
    fn indent_writer_produces_indented_lines() {
        let mut w = IndentWriter::new();
        w.line("fn foo() {");
        w.indent();
        w.line("let x = 1;");
        w.dedent();
        w.line("}");
        let s = w.finish();
        assert!(s.contains("    let x = 1;"));
        assert!(s.contains("fn foo() {"));
        assert!(s.contains("}"));
    }

    #[test]
    fn device_struct_emits_fields() {
        use std::sync::Arc;
        use crate::lexer::token::{Ident, Span};
        let span = Span::new(Arc::new("t.fe".into()), 1, 1, 1);
        let program = {
            Program {
                config:    None,
                defines: vec![DefineItem {
                    name: Ident::new("Led", span.clone()),
                    spec: DeviceSpec::Composite(vec![
                        InterfaceSpec { interface: InterfaceType::Output, qualifier: None,                       span: span.clone() },
                        InterfaceSpec { interface: InterfaceType::Pwm,    qualifier: Some(Qualifier::Brightness), span: span.clone() },
                    ]),
                    span: span.clone(),
                }],
                creates:   vec![],
                declares:  vec![],
                functions: vec![],
                run:       RunSection { items: vec![], span: span.clone() },
                span,
            }
        };
        let ctx    = ctx();
        let output = Emitter::new(&ctx).emit(&program);
        assert!(output.contains("pub struct Led {"));
        assert!(output.contains("pub output:"));
        assert!(output.contains("pub brightness:"));
        assert!(output.contains("pub fn new("));
    }
}