// Runtime crate root.
//
// This crate is a dependency of every program generated by the
// Ferrum compiler. It provides:
//   - Hardware abstraction traits (traits.rs)
//   - EVERY polling scheduler (scheduler.rs)
//   - Button debounce helper (debounce.rs)
//   - Board support implementations (boards/)
//
// The crate is no_std — it runs on bare metal.
// std features (heap allocation, threads) are never used.

#![no_std]

pub mod boards;
pub mod debounce;
pub mod scheduler;
pub mod traits;

// Re-export the most commonly used items at the crate root
// so generated code can write `ferrum_runtime::FerrumOutput`
// instead of `ferrum_runtime::traits::FerrumOutput`.
pub use debounce::Debouncer;
pub use scheduler::{Scheduler, SchedulerSlot};
pub use traits::{
    FerrumAnalog, FerrumDelay, FerrumDisplay,
    FerrumInput, FerrumOutput, FerrumPwm, FerrumPulse,
};